name: BOB
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ls
      - run: echo "Ce workflow a été trigger sur un évènement de type ${{ github.event_name }}"
      - run: echo "Il a été déclenché par ${{ github.actor }}"
      - run: echo "SHA du commit ${{ github.sha }}"
      - run: echo "nom du workflow ${{ github.workflow }}"
      - run: echo "Architecture du runner ${{ runner.arch }}"
      - run: echo "Repertoir du runner ${{ env.HOME }}"