name: BOB
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ls
      - run: echo "Ce workflow a été trigger sur un évènement de type ${{ github.event_name }}"
