name: BOB
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  view:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4.2.2
      -run: ls
